import{a as b,i as v}from"./assets/vendor-s9u5-7p2.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))n(r);new MutationObserver(r=>{for(const i of r)if(i.type==="childList")for(const c of i.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&n(c)}).observe(document,{childList:!0,subtree:!0});function s(r){const i={};return r.integrity&&(i.integrity=r.integrity),r.referrerPolicy&&(i.referrerPolicy=r.referrerPolicy),r.crossOrigin==="use-credentials"?i.credentials="include":r.crossOrigin==="anonymous"?i.credentials="omit":i.credentials="same-origin",i}function n(r){if(r.ep)return;r.ep=!0;const i=s(r);fetch(r.href,i)}})();const p=document.querySelector(".furniture-list"),$=document.querySelector(".loader"),f=document.getElementById("categoriesList"),m=document.getElementById("load-more"),A="https://furniture-store.b.goit.study/api",M=[{src:"../img/Furniture-img/1_1x-min.png",src2x:"../img/Furniture-img/1_2x-min.png",alt:"Опис зображення"},{src:"../img/Furniture-img/2_1x-min.png",src2x:"../img/Furniture-img/2_2x-min.png",alt:"Опис зображення"},{src:"../img/Furniture-img/3_1x-min.png",src2x:"../img/Furniture-img/3_2x-min.png",alt:"Опис зображення"},{src:"../img/Furniture-img/4_1x-min.png",src2x:"../img/Furniture-img/4_2x-min.png",alt:"Опис зображення"},{src:"../img/Furniture-img/5_1x-min.png",src2x:"../img/Furniture-img/5_2x-min.png",alt:"Опис зображення"},{src:"../img/Furniture-img/6_1x-min.png",src2x:"../img/Furniture-img/6_2x-min.png",alt:"Опис зображення"},{src:"../img/Furniture-img/7_1x-min.png",src2x:"../img/Furniture-img/7_2x-min.png",alt:"Опис зображення"},{src:"../img/Furniture-img/8_1x-min.png",src2x:"../img/Furniture-img/8_2x-min.png",alt:"Опис зображення"},{src:"../img/Furniture-img/9_1x-min.png",src2x:"../img/Furniture-img/9_2x-min.png",alt:"Опис зображення"},{src:"../img/Furniture-img/10_1x-min.png",src2x:"../img/Furniture-img/10_2x-min.png",alt:"Опис зображення"},{src:"../img/Furniture-img/11_1x-min.png",src2x:"../img/Furniture-img/11_2x-min.png",alt:"Опис зображення"},{src:"../img/Furniture-img/12_1x-min.png",src2x:"../img/Furniture-img/12_2x-min.png",alt:"Опис зображення"},{src:"../img/Furniture-img/13_1x-min.png",src2x:"../img/Furniture-img/13_2x-min.png",alt:"Опис зображення"}];let L=[],u="0",g=1;const x=8;let a=0,l=0;async function E(){try{return(await b.get(`${A}/categories`)).data}catch{return v.error({message:"Сталася помилка при отриманні категорій",position:"topRight"}),[]}}function O(e,t,s){if(!e||!t)return"";const n=`
    <li class="category-item special-category wrapper_category ${s==="0"?"active":""}" data-id="0">
      <img class="img_category" src="${t[0]?.src}" srcset="${t[0]?.src2x} 2x" alt="${t[0]?.alt}" />
      <p class="text_category">Всі товари</p>
    </li>
  `,r=e.map(({_id:i,name:c},o)=>`
      <li class="category-item wrapper_category ${s===i?"active":""}" data-id="${i}">
        <img class="img_category" src="${t[o+1]?.src}" srcset="${t[o+1]?.src2x} 2x" alt="${c}" />
        <p class="text_category">${c}</p>
      </li>
    `).join("");return n+r}async function y({category:e="0",page:t=2,limit:s=8}={}){$.classList.remove("is-hidden");try{const n={page:t,limit:s};e!=="0"&&(n.category=e);const r=await b.get(`${A}/furnitures`,{params:n});console.log(r);const i=r.data.furnitures||[],c=r.data.total||0;return{furnitures:i,total:c}}catch{return v.error({message:"Помилка отримання меблів",position:"topRight"}),{furnitures:[],total:0}}finally{$.classList.add("is-hidden")}}function h(e,t=!1){if(t||(p.innerHTML=""),!Array.isArray(e)||e.length===0){t||(p.innerHTML="<p>Товари відсутні в цій категорії</p>");return}const s=e.map(({_id:n,name:r,price:i,images:c,color:o})=>{const w=Array.isArray(o)&&o.length>0?o.map(d=>{const _=d.replace(/[^a-zA-Z0-9]/g,"");return`
                  <div class="color-checkbox">
                    <input type="checkbox" id="color-${n}-${_}" name="color-${n}" value="${d}" />
                    <label for="color-${n}-${_}" style="background-color: ${d};" title="${d}"></label>
                  </div>
                `}).join(""):"";return`
        <li class="furniture-item" data-id="${n}">
          <img class="furniture-img" src="${c[0]||""}" alt="${r}" />
          <h3 class="furniture-subtitle">${r}</h3>
          <div class="color-checkboxes">${w}</div>
          <p class="furniture-text">${i} грн</p>
          <button class="furniture-btn" type="button" data-id="${n}">Детальніше</button>
        </li>
      `}).join("");p.insertAdjacentHTML("beforeend",s)}function F(){a>=l?(m.classList.add("is-hidden"),m.disabled=!0):(m.classList.remove("is-hidden"),m.disabled=!1)}async function P(e){if(e===u)return;u=e,g=1,a=0,f.querySelectorAll(".category-item").forEach(n=>{n.classList.toggle("active",n.dataset.id===e)});const{furnitures:t,total:s}=await y({category:u,page:g,limit:x});l=s||0,a=t.length,h(t,!1),F()}f.addEventListener("click",e=>{const t=e.target.closest("li.category-item");t&&P(t.dataset.id)});m.addEventListener("click",async()=>{if(a>=l)return;g++;const{furnitures:e,total:t}=await y({category:u,page:g,limit:x});l=t||l,a+=e.length,h(e,!0),F()});p.addEventListener("click",e=>{const t=e.target.closest(".furniture-btn");if(!t)return;const s=t.dataset.id;alert(`Відкрити деталі для меблів з id: ${s}`)});async function S(){L=await E(),f.innerHTML=O(L,M,u),g=1,a=0;const{furnitures:e,total:t}=await y({category:u,page:g,limit:x});l=t||0,a=e.length,h(e,!1),F()}S();
//# sourceMappingURL=index.js.map
